### ISSUE TITLE
GGShadowService subscription support 

### ISSUE THREAD

**Issue by QuinnCiccoretti** [aws-samples/aws-greengrass-lambda-functions#209]
Is there any way to configure subscriptions to / from the Local Shadow Service as in [Module 5](https://docs.aws.amazon.com/greengrass/latest/developerguide/config-dev-subs.html)? The lambda I'm working on in #170 will need to interface with the local shadow service, but I'm not sure if there is support for this.

**Comment by timmattison** [comment]
There is support for this but I should have more examples. Converting module 5 to GGP style might be the best way if that’s possible.

This is usually covered by the GGD features. Your deployment can list Greengrass Devices. Those devices are Python scripts and live in the GGDs directory.

See https://github.com/aws-samples/aws-greengrass-lambda-functions/blob/f6ac742bae7170fa8b87f54d72cd87b4550ae555/ggds/discovery-with-shadow/ggd.conf

**Comment by QuinnCiccoretti** [comment]
Awsome! I'll look into this now.
