### ISSUE TITLE
localVolumeResources documentation

### ISSUE THREAD

**Issue by QuinnCiccoretti** [aws-samples/aws-greengrass-lambda-functions#223]
Is there any documentation on how to use localVolumeResources in a lambda's function.conf?

**Comment by QuinnCiccoretti** [comment]
Specifically, is there any string i can put in the localVolumeResources to specify the .groupOwner("groupname") with the builder?

**Comment by QuinnCiccoretti** [comment]
This link shows an example, but I'm still not sure all syntax options

**Comment by timmattison** [comment]
Here's a link to the class that holds these values. It's not true documentation, but you can see that it only contains four items that can be specified: name (how it is referenced in the config), source path (the path on the host), destination path (the path inside the Greengrass Lambda container), and a boolean for read/write (false means read-only).

https://github.com/awslabs/aws-greengrass-provisioner/blob/46621cba37f45583b53a83226554a2baa8477643/src/main/java/com/awslabs/aws/greengrass/provisioner/data/resources/LocalVolumeResource.java
